src/Entity/Team.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints;
use ApiPlatform\Core\Annotation as ApiPlatform;
use Symfony\Component\Serializer\Annotation\Groups;
use App\Validator\Constraints as AppConstraints;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TeamRepository")
 * @Constraints\UniqueEntity(fields={"name","hike"}, message="Team name already taken for this hike")
 * @AppConstraints\UniqueTeam
 * @ApiPlatform\ApiResource(
 *     collectionOperations={"get"},
 *     itemOperations={"get"},
 *     attributes={
 *         "normalization_context"={"groups"={"team"}}
 *     }
 * )
 */
class Team
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @var int|null
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string|null
     */
    private $name;

    /**
     * @var Hike
     * @ORM\ManyToOne(targetEntity="Hike", inversedBy="teams")
     * @ORM\JoinColumn(name="hike_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $hike;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="User", inversedBy="teams")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="Walker", mappedBy="team")
     * @var Collection|Walker[]
     */
    private $walkers;

    /**
     * @ORM\OneToMany(targetEntity="TeamPayment", mappedBy="team")
     * @var Collection|TeamPayment[]
     */
    private $payments;

    /**
     * @ORM\Column(type="boolean")
     * @var boolean
     */
    private $isDropped = false;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime|null
     */
    private $startTime;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @var string|null
     */
    private $teamNumber;

    public function __construct()
    {
        $this->walkers = new ArrayCollection();
        $this->payments = new ArrayCollection();
    }

    /**
     * @Groups({"team"})
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id)
    {
        $this->id = $id;
    }

    /**
     * @Groups({"team"})
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name)
    {
        $this->name = $name;
    }

    /**
     * @Groups({"team"})
     * @return Hike
     */
    public function getHike(): ?Hike
    {
        return $this->hike;
    }

    /**
     * @param Hike $hike
     */
    public function setHike(Hike $hike)
    {
        $this->hike = $hike;
    }

    /**
     * @return User|null
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User $user
     */
    public function setUser(User $user)
    {
        $this->user = $user;
    }

    /**
     * @return Walker[]|Collection
     */
    public function getWalkers()
    {
        return $this->walkers;
    }

    /**
     * @return TeamPayment[]|Collection
     */
    public function getPayments()
    {
        return $this->payments;
    }

    /**
     * @return bool
     */
    public function hasMaxWalkers(): bool
    {
        return $this->walkers->count() >= $this->hike->getMaxWalkers();
    }

    /**
     * @return bool
     */
    public function hasEnoughWalkers(): bool
    {
        return $this->walkers->count() >= $this->hike->getMinWalkers();
    }

    /**
     * @return float
     */
    public function getTotalFees()
    {
        return $this->walkers->count() * $this->hike->getFeePerWalker();
    }

    /**
     * @return float
     */
    public function getFeesDue(): float
    {
        return $this->getTotalFees() - $this->getFeesPaid();
    }

    /**
     * @return float
     */
    public function getFeesPaid(): float
    {
        $paid = 0.0;
        foreach ($this->payments as $payment) {
            if ($payment->isCompleted()) {
                $paid += $payment->getTotalAmount()/100;
            }
        }
        return $paid;
    }

    public function getCompletedPayments(): array
    {
        $completed = [];
        foreach ($this->payments as $payment) {
            if ($payment->isCompleted()) {
                $completed[] = $payment;
            }
        }
        return $completed;
    }

    /**
     * @return bool
     */
    public function hasDueFees()
    {
        return $this->getFeesDue() > 0;
    }

    /**
     * @return string
     */
    public function getPaymentDescription(): string
    {
        return sprintf(
            "Payment for %s (%d walkers) for %s",
            $this->getName(),
            $this->walkers->count(),
            $this->hike->__toString()
        );
    }

    /**
     * @return bool
     */
    public function isDropped(): bool
    {
        return $this->isDropped;
    }

    /**
     * @param bool $isDropped
     */
    public function setIsDropped(bool $isDropped): void
    {
        $this->isDropped = $isDropped;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        $string = $this->name;

        if ($this->isDropped) {
            $string .= " (dropped out)";
        }

        return $string;
    }

    /**
     * @return \DateTime|null
     */
    public function getStartTime(): ?\DateTime
    {
        return $this->startTime;
    }

    /**
     * @param \DateTime|null $startTime
     */
    public function setStartTime(?\DateTime $startTime): void
    {
        $this->startTime = $startTime;
    }

    /**
     * @return string|null
     */
    public function getTeamNumber(): ?string
    {
        return $this->teamNumber;
    }

    /**
     * @param string|null $teamNumber
     */
    public function setTeamNumber(?string $teamNumber): void
    {
        $this->teamNumber = $teamNumber;
    }
}

src/Entity/Walker.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WalkerRepository")
 * @UniqueEntity(fields={"referenceCharacter","team"})
 */
class Walker
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=1, options={"fixed" = true})
     * @var string
     */
    private $referenceCharacter;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string
     */
    private $foreName;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string
     */
    private $surName;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string
     */
    private $emergencyContactNumber;

    /**
     * @var Team
     * @ORM\ManyToOne(targetEntity="Team", inversedBy="walkers")
     * @ORM\JoinColumn(name="team_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $team;

    /**
     * @ORM\Column(type="date")
     * @var \DateTime
     */
    private $dateOfBirth;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getForeName(): ?string
    {
        return $this->foreName;
    }

    /**
     * @param string $foreName
     */
    public function setForeName(string $foreName)
    {
        $this->foreName = $foreName;
    }

    /**
     * @return string|null
     */
    public function getSurName(): ?string
    {
        return $this->surName;
    }

    /**
     * @param string $surName
     */
    public function setSurName(string $surName)
    {
        $this->surName = $surName;
    }

    /**
     * @return string|null
     */
    public function getEmergencyContactNumber(): ?string
    {
        return $this->emergencyContactNumber;
    }

    /**
     * @param string $emergencyContactNumber
     */
    public function setEmergencyContactNumber(string $emergencyContactNumber)
    {
        $this->emergencyContactNumber = $emergencyContactNumber;
    }

    /**
     * @return Team|null
     */
    public function getTeam(): ?Team
    {
        return $this->team;
    }

    /**
     * @param Team $team
     */
    public function setTeam(Team $team)
    {
        $this->team = $team;
    }

    /**
     * @return string|null
     */
    public function getReferenceCharacter(): ?string
    {
        return $this->referenceCharacter;
    }

    /**
     * @param string $referenceCharacter
     */
    public function setReferenceCharacter(string $referenceCharacter)
    {
        $this->referenceCharacter = $referenceCharacter;
    }

    /**
     * @return string
     */
    public function getReference(): string
    {
        if (null === $teamNumber = $this->team->getTeamNumber()) {
            return $this->referenceCharacter;
        }
        return $teamNumber . $this->referenceCharacter;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->foreName . ' ' . $this->surName;
    }
    
    public function __toString()
    {
        return $this->getName();
    }

    /**
     * @return \DateTime|null
     */
    public function getDateOfBirth(): ?\DateTime
    {
        return $this->dateOfBirth;
    }

    /**
     * @param \DateTime $dateOfBirth
     */
    public function setDateOfBirth(\DateTime $dateOfBirth): void
    {
        $this->dateOfBirth = $dateOfBirth;
    }

    /**
     * @return null|float
     */
    public function getAgeOnHike(): ?float
    {
        if (is_null($this->dateOfBirth)) {
            return null;
        }

        $interval = $this->dateOfBirth->diff($this->team->getHike()->getEvent()->getDate());
        return floatval($interval->y) + floatval($interval->m)/12;
    }

    /**
     * @return null|string
     */
    public function getReadableAgeOnHike(): ?string
    {
        if (is_null($this->dateOfBirth)) {
            return null;
        }

        $interval = $this->dateOfBirth->diff($this->team->getHike()->getEvent()->getDate());
        return sprintf("%d years %d months", $interval->y, $interval->m);
    }

    /**
     * @Constraints\Callback
     * @param ExecutionContextInterface $context
     */
    public function validate(ExecutionContextInterface $context)
    {
        if ($this->getAgeOnHike() > $this->team->getHike()->getMaxAge()) {
            $context->buildViolation('This walker is too old to enter this event')
                ->atPath('dateOfBirth')
                ->addViolation();
        }

        if ($this->getAgeOnHike() < $this->team->getHike()->getMinAge()) {
            $context->buildViolation('This walker is too young to enter this event')
                ->atPath('dateOfBirth')
                ->addViolation();
        }
    }
}

src/Controller/Team/TeamAssignStartTimeController.php
<?php


namespace App\Controller\Team;

use App\Entity\Team;
use App\Factory\ResponseFactory;
use App\Form\Team\TeamStartTimeType;
use App\Repository\TeamRepository;
use App\Service\NextTeamStartTimeService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\Form\FormInterface;

class TeamAssignStartTimeController
{
    /**
     * @var TeamRepository
     */
    private $teamRepository;

    /**
     * @var FlashBagInterface
     */
    private $flashBag;

    /**
     * @var ResponseFactory
     */
    private $responseFactory;

    /**
     * @var FormFactoryInterface
     */
    private $formFactory;

    /**
     * @var EntityManagerInterface
     */
    private $entityManager;
    /**
     * @var NextTeamStartTimeService
     */
    private $nextTeamStartTimeService;

    /**
     * @var \Swift_Mailer
     */
    private $mailer;

    /**
     * @var \Twig_Environment
     */
    private $twig;

    /**
     * @var string
     */
    private $sender;

    /**
     * @param TeamRepository $teamRepository
     * @param FlashBagInterface $flashBag
     * @param ResponseFactory $responseFactory
     * @param FormFactoryInterface $formFactory
     * @param EntityManagerInterface $entityManager
     * @param NextTeamStartTimeService $nextTeamStartTimeService
     * @param \Swift_Mailer $mailer
     * @param \Twig_Environment $twig
     * @param string $sender
     */
    public function __construct(
        TeamRepository $teamRepository,
        FlashBagInterface $flashBag,
        ResponseFactory $responseFactory,
        FormFactoryInterface $formFactory,
        EntityManagerInterface $entityManager,
        NextTeamStartTimeService $nextTeamStartTimeService,
        \Swift_Mailer $mailer,
        \Twig_Environment $twig,
        string $sender
    ) {
        $this->teamRepository = $teamRepository;
        $this->flashBag = $flashBag;
        $this->responseFactory = $responseFactory;
        $this->formFactory = $formFactory;
        $this->entityManager = $entityManager;
        $this->nextTeamStartTimeService = $nextTeamStartTimeService;
        $this->mailer = $mailer;
        $this->twig = $twig;
        $this->sender = $sender;
    }

    /**
     * @param Request $request
     * @return Response
     * @throws \Twig_Error
     */
    public function __invoke(Request $request): Response
    {
        $teamId = $request->get('team_id');
        $team = $this->teamRepository->find($teamId);

        if (is_null($team)) {
            throw new NotFoundHttpException(sprintf("No team found with the id %d", $teamId));
        }

        if ($team->getStartTime() !== null) {
            $this->flashBag->add('warning', sprintf(
                "Team \"%s\" already assigned start time",
                $team->getName()
            ));

            return $this->responseFactory->createRedirectResponse('hike_teams', [
                'hike_id' => $team->getHike()->getId()
            ]);
        }

        $team->setStartTime($this->nextTeamStartTimeService->getNextTeamStartTimeForHike($team->getHike()));

        $form = $this->formFactory->create(TeamStartTimeType::class, $team);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $this->entityManager->flush();

                $message = (new \Swift_Message())
                    ->setSubject(sprintf("Start Time Assigned for Team %s", $team->getName()))
                    ->setTo($team->getUser()->getEmail())
                    ->setFrom($this->sender)
                    ->setBody(
                        $this->twig->render(
                            'emails/start-time-assigned.html.twig',
                            ['team' => $team]
                        ),
                        'text/html'
                    )
                ;

                $this->mailer->send($message);

                $this->flashBag->add('success', sprintf(
                    "Team \"%s\" successfully updated for \"%s\"",
                    $team->getName(),
                    $team->getHike()->__toString()
                ));

                return $this->responseFactory->createRedirectResponse('hike_teams', [
                    'hike_id' => $team->getHike()->getId()
                ]);
            }

            $this->flashBag->add('danger', "There were some problems with the information you provided");
        }

        return $this->responseFactory->createTemplateResponse('admin/teams/assign-start-time.html.twig', [
            'team' => $team,
            'form' => $form->createView()
        ]);
    }
}

src/Controller/Team/TeamDropController.php
<?php

namespace App\Controller\Team;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class TeamDropController
{

    /**
     * @param Request $request
     * @return Response
     */
    public function __invoke(Request $request): Response
    {
        // TODO: Implement Team Drop
        return new Response("Unimplemented");
    }
}

src/Controller/Team/TeamListController.php
<?php

namespace App\Controller\Team;

use App\Factory\ResponseFactory;
use App\Service\CurrentUserService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class TeamListController
{

    /**
     * @var CurrentUserService
     */
    private $currentUserService;

    /**
     * @var ResponseFactory
     */
    private $responseFactory;

    /**
     * @param CurrentUserService $currentUserService
     * @param ResponseFactory $responseFactory
     */
    public function __construct(CurrentUserService $currentUserService, ResponseFactory $responseFactory)
    {
        $this->currentUserService = $currentUserService;
        $this->responseFactory = $responseFactory;
    }

    /**
     * @param Request $request
     * @return Response
     * @throws \Twig_Error
     */
    public function __invoke(Request $request): Response
    {
        return $this->responseFactory->createTemplateResponse('teams/list.html.twig', [
            'teams' => $this->currentUserService->getCurrentUser()->getTeams()
        ]);
    }
}

templates/teams/create.html.twig
{% extends "_simple_form.html.twig" %}

{% block title %}Register Team &raquo; {{ parent() }}{% endblock %}

{% block header_h1 %}Register Team{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('team_list') }}">Your Teams</a></li>
            <li class="breadcrumb-item active" aria-current="page">Register Team</li>
        </ol>
    </nav>
{% endblock %}

{% block form %}
    {{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.hike) }}

    <button type="submit" class="btn btn-primary btn-raised">Save</button>
    {{ form_end(form) }}
{% endblock %}

templates/teams/drop.html.twig
{% extends "_simple_form.html.twig" %}

{% block title %}Drop {{ team }} &raquo; {{ parent() }}{% endblock %}

{% block header_h1 %}Drop Team "{{ team }}"{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('team_list') }}">Your Teams</a></li>
            <li class="breadcrumb-item"><a href="{{ path('team_show', {'team_id': team.id}) }}">{{ team }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Drop Team "{{ team }}"</li>
        </ol>
    </nav>
{% endblock %}

{% block form %}
    {{ form_start(form) }}
    <h3>Warning!</h3>
    <p>You are about to drop the team "{{ team }}" from the event. Please confirm to proceed</p>
    <button type="submit" class="btn btn-danger btn-raised">Drop</button>
    <a href="{{ path('team_show', {'team_id': team.id}) }}" class="btn btn-default btn-raised">Cancel</a>
    {{ form_end(form) }}
{% endblock %}

templates/teams/reinstate.html.twig
{% extends "_simple_form.html.twig" %}

{% block title %}Reinstate {{ team }} &raquo; {{ parent() }}{% endblock %}

{% block header_h1 %}Reinstate Team "{{ team }}"{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('team_list') }}">Your Teams</a></li>
            <li class="breadcrumb-item"><a href="{{ path('team_show', {'team_id': team.id}) }}">{{ team }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Reinstate Team "{{ team }}"</li>
        </ol>
    </nav>
{% endblock %}

{% block form %}
    {{ form_start(form) }}
    <h3>Please confirm</h3>
    <p>You are about to reinstate the team "{{ team }}" in the event. Please confirm to proceed</p>
    <button type="submit" class="btn btn-success btn-raised">Reinstate</button>
    <a href="{{ path('team_show', {'team_id': team.id}) }}" class="btn btn-default btn-raised">Cancel</a>
    {{ form_end(form) }}
{% endblock %}

templates/teams/show.html.twig
{% extends "_base.html.twig" %}

{% block title %}{{ team.name }} &raquo; {{ parent() }}{% endblock %}

{% block header_h1 %}{{ team }}{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('team_list') }}">Your Teams</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ team.name }}</li>
        </ol>
    </nav>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-4 col-md-5 d-flex">
            <div class="card mb-4 w-100">
                <div class="card-body d-flex flex-column align-items-start">
                    <h5 class="card-title">Basic info</h5>
                    <div class="card-text mb-auto">
                        <dl class="dl">
                            <dt>Team Name</dt>
                            <dd>
                                {{ team.name }}
                                {% if team.isDropped %}
                                    <span class="badge badge-danger">Dropped out</span>
                                {% endif %}
                            </dd>
                            <dt>Team Number</dt>
                            <dd>{{ team.teamNumber ?? 'To be assigned' }}</dd>
                            <dt>Start Time</dt>
                            <dd>
                                {%  if team.startTime is not null %}
                                    {{ team.startTime.format('h:i A F jS, Y') }}
                                {% else %}
                                    To be assigned
                                {% endif %}
                            </dd>
                            <dt>Fees Paid</dt>
                            <dd>£{{ team.feesPaid }}</dd>
                            <dt>Hike</dt>
                            <dd>{{ team.hike }}</dd>
                        </dl>
                        <p class="text-small">Please make sure that each team member has a copy of the
                            <a href="{{ team.hike.kitListURL }}">Kit List</a> and
                            <a href="{{ team.hike.joiningInfoURL }}">Joining Information</a>
                            which they  should also bring on the day.</p>
                    </div>
                    <div class="card-btns">
                        <a
                                href="{{ path('team_update', {'team_id': team.id}) }}"
                                class="text-primary text-uppercase font-brand mr-3"
                        >Update basic info</a>
                        {% if team.isDropped %}
                            <a
                                    href="{{ path('team_reinstate', {'team_id': team.id}) }}"
                                    class="text-success text-uppercase font-brand"
                            >Reinstate team</a>
                        {% else %}
                        <a
                                href="{{ path('team_drop', {'team_id': team.id}) }}"
                                class="text-danger text-uppercase font-brand"
                        >Drop team</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-5 col-md-7 d-flex">
            <div class="card mb-4 w-100">
                <div class="card-body d-flex flex-column align-items-start">
                    <h5 class="card-title">Walkers</h5>
                    {% if team.walkers is not empty %}
                    <table id="walkers" class="table table-sm walkers-table mb-auto">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Age on Hike</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for walker in team.walkers %}
                            <tr class="walkers-table__walker">
                                <td class="walkers-table__reference">#{{ walker.reference }}</td>
                                <td class="walkers-table__name">{{ walker.name }}</td>
                                <td class="walkers-table__age">{{ walker.readableAgeOnHike }}</td>
                                <td class="walkers-table__actions">
                                    <a href="{{ path('walker_update', {'walker_id': walker.id}) }}">Update</a>
                                    <a href="{{ path('walker_delete', {'walker_id': walker.id}) }}">Delete</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                        <p class="mb-auto">This team doesn't have any walkers.</p>
                    {% endif %}
                    <div class="card-btns">
                        <a
                                href="{{ path('walker_create', {'team_id': team.id}) }}"
                                class="text-success text-uppercase font-brand"
                        >Add walker</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 d-flex">
            <div class="card bg-primary text-white mb-4 w-100">
                <div class="card-body d-flex flex-column align-items-start">
                    <h5 class="card-title">Checklist</h5>
                    <ol class="mb-4">
                        <li>
                            Register team
                            <i class="fa fa-check"></i>
                        </li>
                        <li>
                            Add {{ team.hike.minWalkers }} - {{ team.hike.maxWalkers }} walkers
                            {% if team.hasEnoughWalkers %}<i class="fa fa-check"></i>{% endif %}
                        </li>
                        <li>
                            Pay fees
                            {% if team.hasEnoughWalkers and not team.hasDueFees %}<i class="fa fa-check"></i>{% endif %}
                        </li>
                    </ol>
                    {% if team.hasEnoughWalkers and not team.isDropped %}
                        {%  if team.hasDueFees %}
                            <div class="m-auto">
                                <a
                                    href="{{ path('team_payment_capture',  {'team_id': team.id}) }}"
                                    class="btn btn-lg btn-raised btn-light text-dark mx-auto"
                                    id="payment-btn"
                                >Pay £{{ team.feesDue }}</a>
                            </div>
                        {% else %}
                            <div class="mb-0 mt-auto">
                                {% if team.startTime %}
                                    Your team is now fully registered and <strong>their start time is
                                    {{ team.startTime.format('h:i A') }}</strong>. We will contact you over email with more
                                    details.
                                {% else %}
                                    We have received all due payment. You will receive an email once we have assigned
                                    you your start time.
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>

            <div class="modal fade" id="payment-modal" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Payment Instructions</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Please pay using one of the payment methods below. We will email you to confirm that
                            we have received payment</p>
                            <h5>Pay by bank transfer</h5>
                            <p>
                                <strong>Bank:</strong> HSBC<br/>
                                <strong>Sort Code:</strong> 40-38-04<br/>
                                <strong>Account Number:</strong> 11508946<br/>
                                <em>
                                    Please use the reference 3T followed by either your group name or team name. Please
                                    then email <a href="mailto:will@arslett.uk">will@arslett.uk</a>
                                    to let us know you have paid and the reference you used.
                                </em>
                            </p>
                            <h5>Pay by cheque</h5>
                            <p>Please send all cheques to Ferncroft, New Lane Hill, Reading, RG30 4JN.
                                Made payable to Three Towers Hike and clearly labelled with your team name</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {%  if team.completedPayments is not empty %}
        <div class="col-12 d-flex">
            <div class="card mb-4 w-100">
                <div class="card-body d-flex flex-column align-items-start">
                    <h5 class="card-title">Payments Received</h5>
                    <table id="payments" class="table table-sm payments-table mb-auto">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Amount</th>
                            <th scope="col">Date</th>
                            <th scope="col">Time</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for payment in team.completedPayments %}
                            <tr class="payments-table__payment">
                                <td class="payments-table__">#{{ payment.id }}</td>
                                <td class="payments-table__amount">{{ payment.totalAmount / 100 }} {{ payment.currencyCode }}</td>
                                <td class="payments-table__date">{{ payment.date.format('jS F Y') }}</td>
                                <td class="payments-table__time">{{ payment.date.format('h:i:s A') }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}