src/Entity/Team.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints;
use ApiPlatform\Core\Annotation as ApiPlatform;
use Symfony\Component\Serializer\Annotation\Groups;
use App\Validator\Constraints as AppConstraints;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TeamRepository")
 * @Constraints\UniqueEntity(fields={"name","hike"}, message="Team name already taken for this hike")
 * @AppConstraints\UniqueTeam
 * @ApiPlatform\ApiResource(
 *     collectionOperations={"get"},
 *     itemOperations={"get"},
 *     attributes={
 *         "normalization_context"={"groups"={"team"}}
 *     }
 * )
 */
class Team
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @var int|null
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string|null
     */
    private $name;

    /**
     * @var Hike
     * @ORM\ManyToOne(targetEntity="Hike", inversedBy="teams")
     * @ORM\JoinColumn(name="hike_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $hike;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="User", inversedBy="teams")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="Walker", mappedBy="team")
     * @var Collection|Walker[]
     */
    private $walkers;

    /**
     * @ORM\OneToMany(targetEntity="TeamPayment", mappedBy="team")
     * @var Collection|TeamPayment[]
     */
    private $payments;

    /**
     * @ORM\Column(type="boolean")
     * @var boolean
     */
    private $isDropped = false;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime|null
     */
    private $startTime;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @var string|null
     */
    private $teamNumber;

    public function __construct()
    {
        $this->walkers = new ArrayCollection();
        $this->payments = new ArrayCollection();
    }

    /**
     * @Groups({"team"})
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id)
    {
        $this->id = $id;
    }

    /**
     * @Groups({"team"})
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name)
    {
        $this->name = $name;
    }

    /**
     * @Groups({"team"})
     * @return Hike
     */
    public function getHike(): ?Hike
    {
        return $this->hike;
    }

    /**
     * @param Hike $hike
     */
    public function setHike(Hike $hike)
    {
        $this->hike = $hike;
    }

    /**
     * @return User|null
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User $user
     */
    public function setUser(User $user)
    {
        $this->user = $user;
    }

    /**
     * @return Walker[]|Collection
     */
    public function getWalkers()
    {
        return $this->walkers;
    }

    /**
     * @return TeamPayment[]|Collection
     */
    public function getPayments()
    {
        return $this->payments;
    }

    /**
     * @return bool
     */
    public function hasMaxWalkers(): bool
    {
        return $this->walkers->count() >= $this->hike->getMaxWalkers();
    }

    /**
     * @return bool
     */
    public function hasEnoughWalkers(): bool
    {
        return $this->walkers->count() >= $this->hike->getMinWalkers();
    }

    /**
     * @return float
     */
    public function getTotalFees()
    {
        return $this->walkers->count() * $this->hike->getFeePerWalker();
    }

    /**
     * @return float
     */
    public function getFeesDue(): float
    {
        return $this->getTotalFees() - $this->getFeesPaid();
    }

    /**
     * @return float
     */
    public function getFeesPaid(): float
    {
        $paid = 0.0;
        foreach ($this->payments as $payment) {
            if ($payment->isCompleted()) {
                $paid += $payment->getTotalAmount()/100;
            }
        }
        return $paid;
    }

    public function getCompletedPayments(): array
    {
        $completed = [];
        foreach ($this->payments as $payment) {
            if ($payment->isCompleted()) {
                $completed[] = $payment;
            }
        }
        return $completed;
    }

    /**
     * @return bool
     */
    public function hasDueFees()
    {
        return $this->getFeesDue() > 0;
    }

    /**
     * @return string
     */
    public function getPaymentDescription(): string
    {
        return sprintf(
            "Payment for %s (%d walkers) for %s",
            $this->getName(),
            $this->walkers->count(),
            $this->hike->__toString()
        );
    }

    /**
     * @return bool
     */
    public function isDropped(): bool
    {
        return $this->isDropped;
    }

    /**
     * @param bool $isDropped
     */
    public function setIsDropped(bool $isDropped): void
    {
        $this->isDropped = $isDropped;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        $string = $this->name;

        if ($this->isDropped) {
            $string .= " (dropped out)";
        }

        return $string;
    }

    /**
     * @return \DateTime|null
     */
    public function getStartTime(): ?\DateTime
    {
        return $this->startTime;
    }

    /**
     * @param \DateTime|null $startTime
     */
    public function setStartTime(?\DateTime $startTime): void
    {
        $this->startTime = $startTime;
    }

    /**
     * @return string|null
     */
    public function getTeamNumber(): ?string
    {
        return $this->teamNumber;
    }

    /**
     * @param string|null $teamNumber
     */
    public function setTeamNumber(?string $teamNumber): void
    {
        $this->teamNumber = $teamNumber;
    }
}

src/Entity/Walker.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WalkerRepository")
 * @UniqueEntity(fields={"referenceCharacter","team"})
 */
class Walker
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=1, options={"fixed" = true})
     * @var string
     */
    private $referenceCharacter;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string
     */
    private $foreName;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string
     */
    private $surName;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string
     */
    private $emergencyContactNumber;

    /**
     * @var Team
     * @ORM\ManyToOne(targetEntity="Team", inversedBy="walkers")
     * @ORM\JoinColumn(name="team_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $team;

    /**
     * @ORM\Column(type="date")
     * @var \DateTime
     */
    private $dateOfBirth;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getForeName(): ?string
    {
        return $this->foreName;
    }

    /**
     * @param string $foreName
     */
    public function setForeName(string $foreName)
    {
        $this->foreName = $foreName;
    }

    /**
     * @return string|null
     */
    public function getSurName(): ?string
    {
        return $this->surName;
    }

    /**
     * @param string $surName
     */
    public function setSurName(string $surName)
    {
        $this->surName = $surName;
    }

    /**
     * @return string|null
     */
    public function getEmergencyContactNumber(): ?string
    {
        return $this->emergencyContactNumber;
    }

    /**
     * @param string $emergencyContactNumber
     */
    public function setEmergencyContactNumber(string $emergencyContactNumber)
    {
        $this->emergencyContactNumber = $emergencyContactNumber;
    }

    /**
     * @return Team|null
     */
    public function getTeam(): ?Team
    {
        return $this->team;
    }

    /**
     * @param Team $team
     */
    public function setTeam(Team $team)
    {
        $this->team = $team;
    }

    /**
     * @return string|null
     */
    public function getReferenceCharacter(): ?string
    {
        return $this->referenceCharacter;
    }

    /**
     * @param string $referenceCharacter
     */
    public function setReferenceCharacter(string $referenceCharacter)
    {
        $this->referenceCharacter = $referenceCharacter;
    }

    /**
     * @return string
     */
    public function getReference(): string
    {
        if (null === $teamNumber = $this->team->getTeamNumber()) {
            return $this->referenceCharacter;
        }
        return $teamNumber . $this->referenceCharacter;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->foreName . ' ' . $this->surName;
    }
    
    public function __toString()
    {
        return $this->getName();
    }

    /**
     * @return \DateTime|null
     */
    public function getDateOfBirth(): ?\DateTime
    {
        return $this->dateOfBirth;
    }

    /**
     * @param \DateTime $dateOfBirth
     */
    public function setDateOfBirth(\DateTime $dateOfBirth): void
    {
        $this->dateOfBirth = $dateOfBirth;
    }

    /**
     * @return null|float
     */
    public function getAgeOnHike(): ?float
    {
        if (is_null($this->dateOfBirth)) {
            return null;
        }

        $interval = $this->dateOfBirth->diff($this->team->getHike()->getEvent()->getDate());
        return floatval($interval->y) + floatval($interval->m)/12;
    }

    /**
     * @return null|string
     */
    public function getReadableAgeOnHike(): ?string
    {
        if (is_null($this->dateOfBirth)) {
            return null;
        }

        $interval = $this->dateOfBirth->diff($this->team->getHike()->getEvent()->getDate());
        return sprintf("%d years %d months", $interval->y, $interval->m);
    }

    /**
     * @Constraints\Callback
     * @param ExecutionContextInterface $context
     */
    public function validate(ExecutionContextInterface $context)
    {
        if ($this->getAgeOnHike() > $this->team->getHike()->getMaxAge()) {
            $context->buildViolation('This walker is too old to enter this event')
                ->atPath('dateOfBirth')
                ->addViolation();
        }

        if ($this->getAgeOnHike() < $this->team->getHike()->getMinAge()) {
            $context->buildViolation('This walker is too young to enter this event')
                ->atPath('dateOfBirth')
                ->addViolation();
        }
    }
}

src/Form/Hike/HikeDeleteType.php
<?php

namespace App\Form\Hike;

use App\Entity\Hike;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HikeDeleteType extends AbstractType
{

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->setMethod('DELETE');
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Hike::class
        ]);
    }
}

src/Controller/Hike/HikeCreateController.php
<?php

namespace App\Controller\Hike;

use App\Factory\ResponseFactory;
use App\FormManager\Hike\HikeCreateFormManager;
use App\Resolver\EventResolver;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;

class HikeCreateController
{

    /**
     * @var EventResolver
     */
    private $eventResolver;

    /**
     * @var HikeCreateFormManager
     */
    private $hikeCreateFormManager;

    /**
     * @var FlashBagInterface
     */
    private $flashBag;

    /**
     * @var ResponseFactory
     */
    private $responseFactory;

    /**
     * @param EventResolver $eventResolver
     * @param HikeCreateFormManager $hikeCreateFormManager
     * @param FlashBagInterface $flashBag
     * @param ResponseFactory $responseFactory
     */
    public function __construct(
        EventResolver $eventResolver,
        HikeCreateFormManager $hikeCreateFormManager,
        FlashBagInterface $flashBag,
        ResponseFactory $responseFactory
    ) {
        $this->eventResolver = $eventResolver;
        $this->hikeCreateFormManager = $hikeCreateFormManager;
        $this->flashBag = $flashBag;
        $this->responseFactory = $responseFactory;
    }

    /**
     * @param Request $request
     * @return Response
     */
    public function __invoke(Request $request): Response
    {
        $event = $this->eventResolver->resolveById($request->get('event_id'));
        $form = $this->hikeCreateFormManager->createForm($event);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $hike = $this->hikeCreateFormManager->processForm($form);

                $this->flashBag->add('success', sprintf(
                    "Hike \"%s\" successfully added to event \"%s\"",
                    $hike->getName(),
                    $event->getName()
                ));

                return $this->responseFactory->createRedirectResponse('event_show', [
                    'event_id' => $event->getId()
                ]);
            }

            $this->flashBag->add('danger', "There were some problems with the information you provided");
        }

        return $this->responseFactory->createTemplateResponse('hikes/create.html.twig', [
            'event' => $event,
            'form' => $form->createView()
        ]);
    }
}

src/Controller/Hike/HikeDeleteController.php
<?php

namespace App\Controller\Hike;

use App\Factory\ResponseFactory;
use App\FormManager\Hike\HikeDeleteFormManager;
use App\Resolver\HikeResolver;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;

class HikeDeleteController
{

    /**
     * @var HikeResolver
     */
    private $hikeResolver;

    /**
     * @var HikeDeleteFormManager
     */
    private $hikeDeleteFormManager;

    /**
     * @var FlashBagInterface
     */
    private $flashBag;

    /**
     * @var ResponseFactory
     */
    private $responseFactory;

    public function __construct(
        HikeResolver $hikeResolver,
        HikeDeleteFormManager $hikeDeleteFormManager,
        FlashBagInterface $flashBag,
        ResponseFactory $responseFactory
    ) {
        $this->hikeResolver = $hikeResolver;
        $this->hikeDeleteFormManager = $hikeDeleteFormManager;
        $this->flashBag = $flashBag;
        $this->responseFactory = $responseFactory;
    }

    /**
     * @param Request $request
     * @return Response
     * @throws \Twig_Error
     */
    public function __invoke(Request $request): Response
    {
        $hike = $this->hikeResolver->resolveById($request->get('hike_id'));

        $form = $this->hikeDeleteFormManager->createForm($hike);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $hike = $this->hikeDeleteFormManager->processForm($form);

                $this->flashBag->add('success', sprintf(
                    "Hike \"%s\" successfully deleted",
                    $hike->getName()
                ));

                return $this->responseFactory->createRedirectResponse('event_show', [
                    'event_id' => $hike->getEvent()->getId()
                ]);
            }

            $this->flashBag->add('danger', "There were some problems with the information you provided");
        }

        return $this->responseFactory->createTemplateResponse('hikes/delete.html.twig', [
            'hike' => $hike,
            'form' => $form->createView()
        ]);
    }
}

src/Controller/Hike/HikeTeamsController.php
<?php


namespace App\Controller\Hike;

use App\Factory\ResponseFactory;
use App\Resolver\HikeResolver;
use App\Service\CurrentUserService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class HikeTeamsController
{

    /**
     * @var HikeResolver
     */
    private $hikeResolver;

    /**
     * @var ResponseFactory
     */
    private $responseFactory;

    /**
     * @param HikeResolver $hikeResolver
     * @param ResponseFactory $responseFactory
     */
    public function __construct(HikeResolver $hikeResolver, ResponseFactory $responseFactory)
    {
        $this->hikeResolver = $hikeResolver;
        $this->responseFactory = $responseFactory;
    }

    /**
     * @param Request $request
     * @return Response
     * @throws \Twig_Error
     */
    public function __invoke(Request $request): Response
    {
        $hike = $this->hikeResolver->resolveById($request->get('hike_id'));
        return $this->responseFactory->createTemplateResponse('hikes/teams.html.twig', [
            'hike' => $hike,
            'teams' => $hike->getTeams()
        ]);
    }
}

templates/hikes/create.html.twig
{% extends "_simple_form.html.twig" %}

{% block title %}New Hike &raquo; {{ parent() }}{% endblock %}

{% block header_h1 %}Add new hike{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('event_list') }}">Events</a></li>
            <li class="breadcrumb-item"><a href="{{ path('event_show', {'event_id': event.id}) }}">{{ event }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add new hike</li>
        </ol>
    </nav>
{% endblock %}

{% block form %}
    {{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.minWalkers) }}
    {{ form_row(form.maxWalkers) }}
    {{ form_row(form.minAge) }}
    {{ form_row(form.maxAge) }}
    {{ form_row(form.feePerWalker) }}
    {{ form_row(form.startTimeInterval) }}
    {{ form_row(form.firstTeamStartTime) }}
    {{ form_row(form.joiningInfoURL) }}
    {{ form_row(form.kitListURL) }}

    <button type="submit" class="btn btn-primary btn-raised">Save</button>
    {{ form_end(form) }}
{% endblock %}

templates/hikes/delete.html.twig
{% extends "_simple_form.html.twig" %}

{% block title %}Delete {{ hike }} &raquo; {{ parent() }}{% endblock %}

{% block header_h1 %}Delete "{{ hike }}"{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('event_list') }}">Your Teams</a></li>
            <li class="breadcrumb-item"><a href="{{ path('event_show', {'event_id': hike.event.id}) }}">{{ hike.event }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Delete "{{ hike }}"</li>
        </ol>
    </nav>
{% endblock %}

{% block form %}
    {{ form_start(form) }}
    <h3>Warning!</h3>
    <p>You are about to delete hike "{{ hike }}". This action cannot be undone. Please confirm if you wish to proceed.</p>
    <button type="submit" class="btn btn-danger btn-raised"><i class="fa fa-trash"></i> Delete</button>
    <a href="{{ path('event_show', {'event_id': hike.event.id}) }}" class="btn btn-default btn-raised">Cancel</a>
    {{ form_end(form) }}
{% endblock %}

templates/hikes/teams.html.twig
{% extends "_base.html.twig" %}

{% block title %}"{{ hike.name }}" Teams &raquo; {{ parent() }}{% endblock %}

{% block header_h1 %}"{{ hike.name }}" Teams{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('event_list') }}">Events</a></li>
            <li class="breadcrumb-item"><a href="{{ path('event_show', {'event_id': hike.event.id}) }}">{{ hike.event }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">"{{ hike.name }}" Teams</li>
        </ol>
    </nav>
{% endblock %}

{% block body %}
    <div id="teams" class="card">
        <div class="card-body">
            {% if teams is empty %}
            No Teams
            {% else %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Team Name</th>
                        <th>Walkers</th>
                        <th>User</th>
                        <th>Payments</th>
                        <th>Team Number</th>
                        <th>Start Time</th>
                    </tr>
                </thead>
                <tbody>
                    {% for team in teams %}
                    <tr class="{% if team.isDropped %}table-danger{% elseif team.hasEnoughWalkers and not team.hasDueFees %}table-success{% endif %}">
                        <td>{{ team.name }}</td>
                        <td>
                            <a href="javascript:void(0)" data-toggle="modal" data-target="#TeamWalkersModal{{ team.id }}">
                                {{ team.walkers|length }} Walkers
                            </a>
                            <div class="modal fade" id="TeamWalkersModal{{ team.id }}" tabindex="-1" role="dialog" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">{{ team.name }} Walkers</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <table id="walkers" class="table table-sm walkers-table mb-auto">
                                                <thead>
                                                <tr>
                                                    <th scope="col">#</th>
                                                    <th scope="col">Name</th>
                                                    <th scope="col">Emergency Contact Number</th>
                                                    <th scope="col">Age on Hike</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for walker in team.walkers %}
                                                    <tr class="walkers-table__walker">
                                                        <td class="walkers-table__reference">#{{ walker.reference }}</td>
                                                        <td class="walkers-table__name">{{ walker.name }}</td>
                                                        <td class="walkers-table__name">{{ walker.emergencyContactNumber }}</td>
                                                        <td class="walkers-table__age">{{ walker.readableAgeOnHike }}</td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td>
                            <a href="javascript:void(0)" data-toggle="modal" data-target="#TeamUserModal{{ team.id }}">
                                {{ team.user.fullName }}
                            </a>
                            <div class="modal fade" id="TeamUserModal{{ team.id }}" tabindex="-1" role="dialog" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">{{ team.user.fullName }}</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <dl class="dl">
                                                <dt>Full Name</dt>
                                                <dd>{{ team.user.fullName }}</dd>
                                                <dt>Email Address</dt>
                                                <dd>{{ team.user.email }}</dd>
                                                <dt>Contact Number</dt>
                                                <dd>{{ team.user.contactNumber }}</dd>
                                            </dl>
                                        </div>
                                        <div class="modal-footer">
                                            <a href="{{ path('registration_root', {'_switch_user': team.user.email}) }}" class="btn btn-warning">Impersonate</a>
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td>
                            <a href="javascript:void(0)" data-toggle="modal" data-target="#TeamPaymentsModal{{ team.id }}">
                                Paid £{{ team.feesPaid }} / £{{ team.totalFees }}
                            </a>
                            <div class="modal fade" id="TeamPaymentsModal{{ team.id }}" tabindex="-1" role="dialog" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Payments receieved for {{ team.name}}</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <table id="payments" class="table table-sm payments-table mb-auto">
                                                <thead>
                                                <tr>
                                                    <th scope="col">#</th>
                                                    <th scope="col">Amount</th>
                                                    <th scope="col">Date</th>
                                                    <th scope="col">Time</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for payment in team.completedPayments %}
                                                    <tr class="payments-table__payment">
                                                        <td class="payments-table__">#{{ payment.id }}</td>
                                                        <td class="payments-table__amount">{{ payment.totalAmount / 100 }} {{ payment.currencyCode }}</td>
                                                        <td class="payments-table__date">{{ payment.date.format('jS F Y') }}</td>
                                                        <td class="payments-table__time">{{ payment.date.format('h:i:s A') }}</td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="modal-footer">
                                            <a href="{{ path('team_payment_create_offline', {'team_id': team.id}) }}" class="btn btn-success">Add Offline Payment</a>
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                        {% if team.teamNumber is null %}
                        <td colspan="2" class="text-center">
                            <a href="{{ path('team_assign_start_time', {'team_id': team.id}) }}">Assign Team Number and Start Time</a>
                        </td>
                        {% else %}
                        <td>
                            {{ team.teamNumber }}
                        </td>
                        <td>
                            <span class="badge badge-success">{{ team.startTime.format('h:i A') }}</span>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
{% endblock %}